theme: jekyll-theme-architect
title: Unveiling the hidden potential of Helsinki: Harnessing green spaces for a thriving city
description: Data Science project on greenspaces and residential segregation in Helsinki
